### PR TITLE
MAUI-2290 UG documentation for SfAvatarView

### PR DESCRIPTION
**Pull request by EwaldJebaraj**
Provided the User Guidelines documentation for SfAvatarView

Prerared UG documentation for the following categories

- Overview
- Getting Started
- Content Type
- Customization
- Visual Styles
- How To
- Migration

### CODE REVIEW

**Comment by EwaldJebaraj** [comment]
rebuild

**Comment by PaulAnderson02** [comment]
rebuild

**Comment by EwaldJebaraj** [comment]
rebuild

**Review by PaulAnderson02 — APPROVED** [review]
Fine

**Comment by EwaldJebaraj** [comment]
This SfAvatarView documentation content was reviewed by FLORENCE LILIAN AWINO

**Pull request merged**
