### PR TITLE
MAUI-2481: How to migrate from Xamarin Forms Maps control to .NET MAUI Maps control.

### PR DESCRIPTION
**Pull request by SVRagul**
Hi @vigneshrameshsync,

I have prepared MD document for the Xamarin SfMaps to .Net MAUI SfMaps. Can you please review and merge this.

Regards,
Ragul S V

### CODE REVIEW

**Comment by vigneshrameshsync** [comment]
rebuild

**Comment by vigneshrameshsync** [comment]
rebuild

**Comment by SVRagul** [comment]
rebuild

**Comment by vigneshrameshsync** [comment]
rebuild

**Comment by vigneshrameshsync** [comment]
rebuild

**Review by vigneshrameshsync — APPROVED** [review]
The content is fine.

**Pull request merged**
