### PR TITLE
MAUI-2286 : Content review changes for Maps.

### PR DESCRIPTION
**Pull request by Shalini-Ashokan**
Hi @vigneshrameshsync ,
I have updated a content in MAUI maps. Could you please review it?

Regards,
Shalini.

### CODE REVIEW

**Comment by vigneshrameshsync** [comment]
rebuild

**Review by vigneshrameshsync — APPROVED** [review]

**Comment by Shalini-Ashokan** [comment]
rebuild

**Comment by Shalini-Ashokan** [comment]
rebuild

**Review by vigneshrameshsync — APPROVED** [review]
The changes are fine.

**Pull request merged**
